[2;32m2016-02-24 11:14:28,565 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:14:30,066 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:14:30,066 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:14:30,066 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:14:30,662 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:14:30,756 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:14:30,772 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:14:30,806 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:14:30,806 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:14:30,853 - INFO  [main:ServerBootstrap@129] - Application PID:	1704
[m[2;35m2016-02-24 11:16:30,870 - WARN  [Thread-2:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :97968, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:22:17,879 - ERROR [Xmemcached-Reactor-2:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:22:17,911 - WARN  [Xmemcached-Reactor-2:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:22:19,919 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;32m2016-02-24 11:23:32,803 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:23:34,191 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:23:34,191 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:23:34,191 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:23:34,928 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:23:35,039 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:23:35,070 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:23:35,085 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:23:35,085 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:23:35,195 - INFO  [main:ServerBootstrap@129] - Application PID:	5256
[m[2;35m2016-02-24 11:23:51,549 - WARN  [Thread-23:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :5988, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:23:52,112 - WARN  [Thread-25:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :10, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:24:13,149 - ERROR [Xmemcached-Reactor-2:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:24:13,180 - WARN  [Xmemcached-Reactor-2:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:24:15,186 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;35m2016-02-24 11:24:16,196 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:24:22,793 - WARN  [Thread-2:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :4899, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:24:22,927 - WARN  [Thread-27:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :35, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:24:23,095 - WARN  [Thread-29:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :8, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:24:35,635 - ERROR [Xmemcached-Reactor-3:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:24:35,651 - WARN  [Xmemcached-Reactor-3:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:24:37,666 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;35m2016-02-24 11:24:38,683 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:24:50,332 - WARN  [Thread-13:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :4176, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:24:50,426 - WARN  [Thread-31:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :24, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:24:50,485 - WARN  [Thread-33:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :44, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:24:58,225 - WARN  [Thread-22:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :16, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:24:58,304 - WARN  [Thread-35:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :4, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:24:58,336 - WARN  [Thread-15:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :14, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:25:04,730 - WARN  [Thread-24:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :0, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:25:04,802 - WARN  [Thread-4:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :3, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:25:04,826 - WARN  [Thread-26:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :9, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:26:54,616 - ERROR [JUICE-SERVER-Handler-4-1-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x72c803cd, /127.0.0.1:51419 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:26:54,634 - ERROR [JUICE-SERVER-Handler-4-3-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0xe3199587, /127.0.0.1:51420 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:26:54,639 - ERROR [JUICE-SERVER-Handler-4-3-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x20a7f11f, /127.0.0.1:51421 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[2;32m2016-02-24 11:27:19,750 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:27:20,531 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:27:20,531 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:27:20,531 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:27:20,962 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:27:21,071 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:27:21,118 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:27:21,134 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:27:21,134 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:27:21,196 - INFO  [main:ServerBootstrap@129] - Application PID:	4844
[m[2;35m2016-02-24 11:27:55,346 - WARN  [Thread-32:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :27341, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:28:05,343 - ERROR [Xmemcached-Reactor-2:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:28:05,374 - WARN  [Xmemcached-Reactor-2:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:28:07,386 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[7;31m2016-02-24 11:28:08,384 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:08,384 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:08,384 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:28:10,388 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 2 times
[m[7;31m2016-02-24 11:28:11,390 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:11,390 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:11,390 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:28:15,398 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 3 times
[m[7;31m2016-02-24 11:28:16,402 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:16,402 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:16,402 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:28:22,417 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 4 times
[m[7;31m2016-02-24 11:28:23,465 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:23,466 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:23,467 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:28:31,468 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 5 times
[m[7;31m2016-02-24 11:28:32,530 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:32,530 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:32,531 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[7;31m2016-02-24 11:28:33,089 - ERROR [Thread-22:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:28:42,541 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 6 times
[m[7;31m2016-02-24 11:28:43,560 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:43,560 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:43,560 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[7;31m2016-02-24 11:28:46,045 - ERROR [Thread-22:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:19)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:46,093 - ERROR [Thread-22:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:24)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:47,785 - ERROR [Thread-22:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:61)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:47,816 - ERROR [Thread-22:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:65)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:47,816 - ERROR [Thread-22:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:28:47,816 - WARN  [Thread-22:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :22678, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:28:55,565 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 7 times
[m[7;31m2016-02-24 11:28:56,564 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:56,564 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:28:56,564 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[7;31m2016-02-24 11:28:57,730 - ERROR [Thread-20:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,731 - ERROR [Thread-20:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:19)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,750 - ERROR [Thread-20:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:24)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,751 - ERROR [Thread-20:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:61)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,759 - ERROR [Thread-20:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:65)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,760 - ERROR [Thread-20:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:28:57,766 - WARN  [Thread-20:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :5331, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:28:57,937 - ERROR [Thread-11:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.OrderReqAO.queryFilterBySpid(OrderReqAO.java:52)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.queryFilterBySpid(CommonActionImpl.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:28:57,958 - ERROR [Thread-11:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.OrderReqAO.queryFilterBySpid(OrderReqAO.java:58)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.queryFilterBySpid(CommonActionImpl.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:28:57,961 - WARN  [Thread-11:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :25, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[7;31m2016-02-24 11:28:58,418 - ERROR [Thread-24:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.addOrderReqInfo(CommonActionImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:28:58,419 - WARN  [Thread-24:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :11, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:29:10,567 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 8 times
[m[7;31m2016-02-24 11:29:11,568 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:11,568 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:11,568 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[7;31m2016-02-24 11:29:16,557 - ERROR [Thread-34:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,558 - ERROR [Thread-34:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:19)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,626 - ERROR [Thread-34:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CPInfoAO.queryCPInfo(CPInfoAO.java:24)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,627 - ERROR [Thread-34:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:61)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,640 - ERROR [Thread-34:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectCodeInfo(CodeHelperAO.java:65)
	at com.klw.fastfun.pay.data.ao.CodeHelperAO.collectAllCode(CodeHelperAO.java:26)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,649 - ERROR [Thread-34:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.getPayCodes(CommonActionImpl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:29:16,661 - WARN  [Thread-34:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :2822, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:29:16,863 - ERROR [Thread-36:MemcachedResource@57] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.fetch0(XMemcachedClient.java:644)
	at net.rubyeye.xmemcached.XMemcachedClient.get0(XMemcachedClient.java:1058)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1016)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1027)
	at net.rubyeye.xmemcached.XMemcachedClient.get(XMemcachedClient.java:1049)
	at com.juice.orange.game.cached.MemcachedResource.get(MemcachedResource.java:55)
	at com.klw.fastfun.pay.data.ao.OrderReqAO.queryFilterBySpid(OrderReqAO.java:52)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.queryFilterBySpid(CommonActionImpl.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[7;31m2016-02-24 11:29:16,882 - ERROR [Thread-36:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.data.ao.OrderReqAO.queryFilterBySpid(OrderReqAO.java:58)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.queryFilterBySpid(CommonActionImpl.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:29:16,883 - WARN  [Thread-36:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :20, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[7;31m2016-02-24 11:29:16,962 - ERROR [Thread-23:MemcachedResource@48] - There is no available connection at this moment
[mnet.rubyeye.xmemcached.exception.MemcachedException: There is no available connection at this moment
	at net.rubyeye.xmemcached.impl.MemcachedConnector.send(MemcachedConnector.java:498)
	at net.rubyeye.xmemcached.XMemcachedClient.sendCommand(XMemcachedClient.java:315)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2494)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1340)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1398)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1385)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:46)
	at com.juice.orange.game.cached.MemcachedResource.save(MemcachedResource.java:41)
	at com.klw.fastfun.pay.common.action.impl.CommonActionImpl.addOrderReqInfo(CommonActionImpl.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.juice.orange.game.rmi.control.RPCServerControl.nextHandler(RPCServerControl.java:57)
	at com.juice.orange.game.util.threadpool.JuiceThreadPool$JuiceWorkThread.run(JuiceThreadPool.java:70)
[2;35m2016-02-24 11:29:16,963 - WARN  [Thread-23:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :35, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:29:27,571 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 9 times
[m[7;31m2016-02-24 11:29:28,575 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:28,575 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:28,575 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:29:46,596 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 10 times
[m[7;31m2016-02-24 11:29:47,616 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:47,616 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:29:47,616 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:30:07,629 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 11 times
[m[7;31m2016-02-24 11:30:08,662 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:30:08,662 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:30:08,662 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:30:30,665 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:30:30,665 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 12 times
[m[2;35m2016-02-24 11:30:36,083 - WARN  [Thread-14:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :5104, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:30:36,176 - WARN  [Thread-9:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :15, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:30:36,222 - WARN  [Thread-7:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :26, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:30:58,393 - WARN  [Thread-38:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :17240, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:31:01,725 - ERROR [Xmemcached-Reactor-3:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:31:01,725 - WARN  [Xmemcached-Reactor-3:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:31:03,727 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;32m2016-02-24 11:31:40,823 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:31:41,647 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:31:41,647 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:31:41,647 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:31:42,574 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:31:42,621 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:31:42,636 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:31:42,652 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:31:42,652 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:31:42,700 - INFO  [main:ServerBootstrap@129] - Application PID:	1144
[m[2;35m2016-02-24 11:32:18,082 - WARN  [Thread-32:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :29287, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:33:07,625 - ERROR [JUICE-SERVER-Handler-4-1-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x584e621f, /127.0.0.1:51739 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:33:07,662 - ERROR [JUICE-SERVER-Handler-4-3-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0xf65e2842, /127.0.0.1:51741 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:33:07,625 - ERROR [JUICE-SERVER-Handler-4-2-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x2fd2a48c, /127.0.0.1:51740 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[2;32m2016-02-24 11:33:32,876 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:33:33,766 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:33:33,766 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:33:33,766 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:33:34,131 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:33:34,178 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:33:34,224 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:33:34,240 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:33:34,240 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:33:34,256 - INFO  [main:ServerBootstrap@129] - Application PID:	5272
[m[2;35m2016-02-24 11:33:36,301 - WARN  [Thread-2:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :120, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:33:36,429 - WARN  [Thread-22:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :16, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:33:36,889 - WARN  [Thread-24:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :15, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:34:07,655 - ERROR [Xmemcached-Reactor-2:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:34:07,686 - WARN  [Xmemcached-Reactor-2:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:34:09,698 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[7;31m2016-02-24 11:34:10,728 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:34:10,728 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:34:10,728 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[2;35m2016-02-24 11:34:12,740 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 2 times
[m[7;31m2016-02-24 11:34:13,742 - ERROR [Heal-Session-Thread:MemcachedConnector$SessionMonitor@169] - Reconnect to 127.0.0.1:11211 fail
[m[7;31m2016-02-24 11:34:13,742 - ERROR [Xmemcached-Reactor-0:MemcachedConnector$InnerControllerStateListener@558] - Exception occured in controller
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[7;31m2016-02-24 11:34:13,742 - ERROR [Xmemcached-Reactor-0:Reactor@325] - Reactor dispatch events error
[mjava.io.IOException: Connect to 127.0.0.1:11211 fail,Connection refused: no further information
	at net.rubyeye.xmemcached.impl.MemcachedConnector.onConnect(MemcachedConnector.java:423)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:303)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;32m2016-02-24 11:34:30,113 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:34:30,925 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:34:30,925 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:34:30,925 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:34:31,385 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:34:31,479 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:34:31,494 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:34:31,526 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:34:31,526 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:34:31,572 - INFO  [main:ServerBootstrap@129] - Application PID:	5668
[m[2;35m2016-02-24 11:35:34,029 - WARN  [Thread-22:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :52202, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[7;31m2016-02-24 11:35:39,766 - ERROR [JUICE-SERVER-Handler-4-2-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x98442f00, /127.0.0.1:51936 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:35:39,766 - ERROR [JUICE-SERVER-Handler-4-1-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0xb395d93e, /127.0.0.1:51934 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:35:39,766 - ERROR [JUICE-SERVER-Handler-4-3-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0xb8894d63, /127.0.0.1:51935 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[2;32m2016-02-24 11:36:16,106 - INFO  [main:ServerBootstrap@78] - connect to database:jdbc:mysql://120.24.88.90:3306/fastfun?useUnicode=true&characterEncoding=UTF-8
[m[2;32m2016-02-24 11:36:16,920 - INFO  [main:ServerBootstrap@104] - Configuration Server bootstrap params.......
[m[2;32m2016-02-24 11:36:16,920 - INFO  [main:ServerBootstrap@105] - Server protocol:	socket
[m[2;32m2016-02-24 11:36:16,920 - INFO  [main:ServerBootstrap@106] - Server port:	9912
[m[2;35m2016-02-24 11:36:17,298 - WARN  [main:XMemcachedClient@727] - XMemcachedClient use Binary protocol
[m[2;32m2016-02-24 11:36:17,345 - INFO  [main:SelectorManager@37] - Creating 4 reactors...
[m[2;35m2016-02-24 11:36:17,345 - WARN  [main:AbstractController@372] - The Controller started at localhost/127.0.0.1:0 ...
[m[2;35m2016-02-24 11:36:17,360 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;32m2016-02-24 11:36:17,360 - INFO  [main:Application@25] - 初始化AO...
[m[2;32m2016-02-24 11:36:17,376 - INFO  [main:ServerBootstrap@129] - Application PID:	5452
[m[7;31m2016-02-24 11:36:29,388 - ERROR [Xmemcached-Reactor-2:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:36:29,404 - WARN  [Xmemcached-Reactor-2:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:36:31,423 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;35m2016-02-24 11:36:32,426 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:36:41,058 - WARN  [Thread-13:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :58, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:36:41,092 - WARN  [Thread-12:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :14, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[2;35m2016-02-24 11:36:45,320 - WARN  [Thread-22:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :0, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:36:45,351 - WARN  [Thread-2:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :11, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:37:10,776 - ERROR [Xmemcached-Reactor-3:MemcachedHandler@138] - XMemcached network layout exception
[mjava.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:203)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:196)
	at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:341)
	at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:56)
	at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:157)
	at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:295)
	at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:142)
[2;35m2016-02-24 11:37:10,776 - WARN  [Xmemcached-Reactor-3:MemcachedConnector@365] - Remove a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:37:12,794 - WARN  [Heal-Session-Thread:MemcachedConnector$SessionMonitor@125] - Trying to connect to 127.0.0.1:11211 for 1 times
[m[2;35m2016-02-24 11:37:13,795 - WARN  [Xmemcached-Reactor-0:MemcachedConnector@251] - Add a session: 127.0.0.1:11211
[m[2;35m2016-02-24 11:37:16,744 - WARN  [Thread-14:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :64, action:com.klw.fastfun.pay.common.action.CommonAction, method:getPayCodes
[m[2;35m2016-02-24 11:37:16,887 - WARN  [Thread-24:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :33, action:com.klw.fastfun.pay.common.action.CommonAction, method:queryFilterBySpid
[m[2;35m2016-02-24 11:37:17,058 - WARN  [Thread-10:JuiceThreadPool$JuiceWorkThread@108] - RPC method start time :35, action:com.klw.fastfun.pay.common.action.CommonAction, method:addOrderReqInfo
[m[7;31m2016-02-24 11:37:54,576 - ERROR [JUICE-SERVER-Handler-4-1-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x0fd53cd9, /127.0.0.1:52051 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:37:54,591 - ERROR [JUICE-SERVER-Handler-4-2-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x53a1e37b, /127.0.0.1:52053 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
[7;31m2016-02-24 11:37:54,591 - ERROR [JUICE-SERVER-Handler-4-1-thread:ConnectionException@22] - uncaughtException :
[mcom.juice.orange.game.exception.JuiceException: 远程主机强迫关闭了一个现有的连接。 on [id: 0x261d5f1a, /127.0.0.1:52052 => /127.0.0.1:9912]
	at com.juice.orange.game.exception.JuiceException.fromException(JuiceException.java:38)
	at com.juice.orange.game.exception.JuiceException.fromExceptionEvent(JuiceException.java:32)
	at com.juice.orange.game.util.ConnectionHelper$2.run(ConnectionHelper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	... 3 more
